my_data <- read.table("household_power_consumption.txt",skip=1,sep=";")
names(my_data) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
my_data2 <- subset(my_data, Date=="1/2/2007" | Date =="2/2/2007")
my_data2$Date <- as.Date(my_data2$Date, format="%d/%m/%Y")
my_data2$Time <- strptime(my_data2$Time, format="%H:%M:%S")
my_data2[1:1440,"Time"] <- format(my_data2[1:1440,"Time"],"2007-02-01 %H:%M:%S")
my_data2[1441:2880,"Time"] <- format(my_data2[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
my_data2$Global_active_power <- as.numeric(my_data2$Global_active_power)
png("plot2.png", width=480, height=480)
plot(my_data2$Time,my_data2$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.off()
