mydata <- read.table("household_power_consumption.txt",skip=1,sep=";")
names(mydata) <- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
mydata2 <- subset(mydata, Date=="1/2/2007" | Date =="2/2/2007")
mydata2$Date <- as.Date(mydata2$Date, format="%d/%m/%Y")
mydata2$Time <- strptime(mydata2$Time, format="%H:%M:%S")
mydata2[1:1440,"Time"] <- format(mydata2[1:1440,"Time"],"2007-02-01 %H:%M:%S")
mydata2[1441:2880,"Time"] <- format(mydata2[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
mydata2$Sub_metering_1 <- as.numeric(mydata2$Sub_metering_1)
png("plot3.png", width=480, height=480)
plot(mydata2$Time,mydata2$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
with(mydata2,lines(Time,Sub_metering_1))
with(mydata2, lines(Time, as.numeric(as.character(Sub_metering_2)), col = "red"))
with(mydata2, lines(Time, as.numeric(as.character(Sub_metering_3)), col = "blue"))
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()